#############################################################################
# Makefile for building: libQsLog.so.2.0.0
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 12? 15 11:40:22 2020
# Project:  QsLogSharedLibrary.pro
# Template: lib
# Command: /usr/local/Trolltech/Qt-x11-4.8.6/bin/qmake -o Makefile QsLogSharedLibrary.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-x11-4.8.6/include/QtCore -I/usr/local/Trolltech/Qt-x11-4.8.6/include -I. -Ibuild-QsLogShared/moc
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.6/lib -shared -Wl,-soname,libQsLog.so.2
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-x11-4.8.6/lib -lQtCore -L/usr/local/Trolltech/Qt-x11-4.8.6/lib -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-x11-4.8.6/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build-QsLogShared/obj/

####### Files

SOURCES       = QsLogDest.cpp \
		QsLog.cpp \
		QsLogDestConsole.cpp \
		QsLogDestFile.cpp \
		QsLogDestFunctor.cpp build-QsLogShared/moc/moc_QsLogDestFunctor.cpp
OBJECTS       = build-QsLogShared/obj/QsLogDest.o \
		build-QsLogShared/obj/QsLog.o \
		build-QsLogShared/obj/QsLogDestConsole.o \
		build-QsLogShared/obj/QsLogDestFile.o \
		build-QsLogShared/obj/QsLogDestFunctor.o \
		build-QsLogShared/obj/moc_QsLogDestFunctor.o
DIST          = /usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/default_pre.prf \
		QsLog.pri \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/shared.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/dll.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/include_source_dir.prf \
		QsLogSharedLibrary.pro
QMAKE_TARGET  = QsLog
DESTDIR       = build-QsLogShared/
TARGET        = libQsLog.so.2.0.0
TARGETA       = build-QsLogShared/libQsLog.a
TARGETD       = libQsLog.so.2.0.0
TARGET0       = libQsLog.so
TARGET1       = libQsLog.so.2
TARGET2       = libQsLog.so.2.0

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  build-QsLogShared/$(TARGET)

build-QsLogShared/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) build-QsLogShared/ || $(MKDIR) build-QsLogShared/ 
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) build-QsLogShared/$(TARGET)
	-$(DEL_FILE) build-QsLogShared/$(TARGET0)
	-$(DEL_FILE) build-QsLogShared/$(TARGET1)
	-$(DEL_FILE) build-QsLogShared/$(TARGET2)
	-$(MOVE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2) build-QsLogShared/



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: QsLogSharedLibrary.pro  /usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/default_pre.prf \
		QsLog.pri \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/shared.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/dll.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-x11-4.8.6/lib/libQtCore.prl
	$(QMAKE) -o Makefile QsLogSharedLibrary.pro
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/default_pre.prf:
QsLog.pri:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/shared.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/dll.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-x11-4.8.6/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile QsLogSharedLibrary.pro

dist: 
	@$(CHK_DIR_EXISTS) build-QsLogShared/obj/QsLog2.0.0 || $(MKDIR) build-QsLogShared/obj/QsLog2.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build-QsLogShared/obj/QsLog2.0.0/ && $(COPY_FILE) --parents QsLogDest.h QsLog.h QsLogDestConsole.h QsLogLevel.h QsLogDestFile.h QsLogDisableForThisFile.h QsLogDestFunctor.h build-QsLogShared/obj/QsLog2.0.0/ && $(COPY_FILE) --parents QsLogDest.cpp QsLog.cpp QsLogDestConsole.cpp QsLogDestFile.cpp QsLogDestFunctor.cpp build-QsLogShared/obj/QsLog2.0.0/ && (cd `dirname build-QsLogShared/obj/QsLog2.0.0` && $(TAR) QsLog2.0.0.tar QsLog2.0.0 && $(COMPRESS) QsLog2.0.0.tar) && $(MOVE) `dirname build-QsLogShared/obj/QsLog2.0.0`/QsLog2.0.0.tar.gz . && $(DEL_FILE) -r build-QsLogShared/obj/QsLog2.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) build-QsLogShared/$(TARGET) 
	-$(DEL_FILE) build-QsLogShared/$(TARGET0) build-QsLogShared/$(TARGET1) build-QsLogShared/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build-QsLogShared/moc/moc_QsLogDestFunctor.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build-QsLogShared/moc/moc_QsLogDestFunctor.cpp
build-QsLogShared/moc/moc_QsLogDestFunctor.cpp: QsLogDest.h \
		QsLogLevel.h \
		QsLogDestFunctor.h
	/usr/local/Trolltech/Qt-x11-4.8.6/bin/moc $(DEFINES) $(INCPATH) QsLogDestFunctor.h -o build-QsLogShared/moc/moc_QsLogDestFunctor.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build-QsLogShared/obj/QsLogDest.o: QsLogDest.cpp QsLogDest.h \
		QsLogLevel.h \
		QsLogDestConsole.h \
		QsLogDestFile.h \
		QsLogDestFunctor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build-QsLogShared/obj/QsLogDest.o QsLogDest.cpp

build-QsLogShared/obj/QsLog.o: QsLog.cpp QsLog.h \
		QsLogLevel.h \
		QsLogDest.h \
		QsLogDisableForThisFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build-QsLogShared/obj/QsLog.o QsLog.cpp

build-QsLogShared/obj/QsLogDestConsole.o: QsLogDestConsole.cpp QsLogDestConsole.h \
		QsLogDest.h \
		QsLogLevel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build-QsLogShared/obj/QsLogDestConsole.o QsLogDestConsole.cpp

build-QsLogShared/obj/QsLogDestFile.o: QsLogDestFile.cpp QsLogDestFile.h \
		QsLogDest.h \
		QsLogLevel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build-QsLogShared/obj/QsLogDestFile.o QsLogDestFile.cpp

build-QsLogShared/obj/QsLogDestFunctor.o: QsLogDestFunctor.cpp QsLogDestFunctor.h \
		QsLogDest.h \
		QsLogLevel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build-QsLogShared/obj/QsLogDestFunctor.o QsLogDestFunctor.cpp

build-QsLogShared/obj/moc_QsLogDestFunctor.o: build-QsLogShared/moc/moc_QsLogDestFunctor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build-QsLogShared/obj/moc_QsLogDestFunctor.o build-QsLogShared/moc/moc_QsLogDestFunctor.cpp

####### Install

install_headers: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/include/$(QMAKE_TARGET)/ || $(MKDIR) $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/include/$(QMAKE_TARGET)/ 
	-$(INSTALL_PROGRAM) /mnt/hgfs/vmware_share/qslog/QsLog.h $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/include/$(QMAKE_TARGET)/
	-strip $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/include/$(QMAKE_TARGET)/QsLog.h
	-$(INSTALL_PROGRAM) /mnt/hgfs/vmware_share/qslog/QsLogDest.h $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/include/$(QMAKE_TARGET)/
	-strip $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/include/$(QMAKE_TARGET)/QsLogDest.h
	-$(INSTALL_PROGRAM) /mnt/hgfs/vmware_share/qslog/QsLogLevel.h $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/include/$(QMAKE_TARGET)/
	-strip $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/include/$(QMAKE_TARGET)/QsLogLevel.h


uninstall_headers:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/include/$(QMAKE_TARGET)/QsLog.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/include/$(QMAKE_TARGET)/QsLogDest.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/include/$(QMAKE_TARGET)/QsLogLevel.h
	-$(DEL_DIR) $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/include/$(QMAKE_TARGET)/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/lib64/ || $(MKDIR) $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/lib64/ 
	-$(INSTALL_PROGRAM) "build-QsLogShared/$(TARGET)" "$(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/lib64/$(TARGET)"
	-$(STRIP) --strip-unneeded "$(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/lib64/$(TARGET)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/lib64/$(TARGET0)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/lib64/$(TARGET1)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/lib64/$(TARGET2)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/lib64/$(TARGET)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/lib64/$(TARGET0)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/lib64/$(TARGET1)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/lib64/$(TARGET2)"
	-$(DEL_DIR) $(INSTALL_ROOT)/mnt/hgfs/vmware_share/qslog/dll/lib64/ 


install:  install_headers install_target  FORCE

uninstall: uninstall_headers uninstall_target   FORCE

FORCE:

